---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgC3uNiRPKVRP7segFJO5KwRHYxtVXO8hE286Gl7pV+UvF4fPADGf91FlbVQi2P/ZY0/Sqkt3Vx0Xy9spUr6azDHrKZb/jVz2uedPRrutAY/mrn3QCSY/oZQNipqIRRrV5bg+F7333kfV13CXjGXeeLOnV5VSWpfOa7f2+AyjRMGoG5d+VS5rbH8BAMLLAwfQy2/f26ygWiq6ooBxln4OExSkwPf9YLGohIVHxytsUCLhhK6cJichjq04hv0yKOukYYzUHlbn9xdJdSz71TKiyqs4RFjeKVtMDsjjZQ0t/XmUp/B7A1FkMG8HlP0uudqIKf9mTOwBJCSe7y1b2q/5Izvn6HPWKbmOzZ9HafpPJmllpUkE5GMLOnSjhre+bO9GiynBWDQmX4325bxJDgxQNATBVisxypilBwKFgt4gqD5+k+UK198HnKOTdAcecZr8Dp1LB79qMIHJxj+gu+pKROEGevttrRkz/DNJoaOnfZ504LDQGu9hueqURCTCkeBNMlHFxOPoySbvcS1xWhLN7BmIncJhDYhgYEkYKV9axpvnVSzMl4bexOec1Q2KivSuX0hfrEivVQzxqFTs9Mu/JoBHcdaL/zo9ZLcJzsUOdlaO2F81IRDeKmaxRl67Z9ZG16F1gUf8QJ+UwniDWt66oE3sRjMKGok5DKzhQPKliLgwcncCkEi7ONeDo7eFxs5VnCQenLIpxVVOVjdp6L/0gkul0V0x6Mskc+t81A=
    RABBITMQ_DEFAULT_USER: AgAUdPGcnTI401bxrRf3FYiEfXQxlRy2+M0puNqJj9Nnbwi7It/7QFcH9fghg/m8f/xBSOcMKprhykuAxP4QUtfHFCcfJOAYvAQo20ZRx27lDQjyc/hWTTNlEvCxVTqbB2UxUxe80WQ9WzJMdVDkGCHSNVf+2cU0N6APjUMt5imRIoo+qAECVOnHFm9vnJRd9GY0x/pseg8SaA1HElKqw47B61mmo8n0Uhw1PcqJBwYG3piqHH8MYJabX3LzjWxNkOCy03ZKxJz5NuLt435KfdCUVYZbbpaq2vaK/2R1Eg41XlEEu+L3DhuDp/Ob6Gv12s+QyDS4qegS7TMsM1eA6XbaxUHzo2TdKo5HMG5eq13AHxgM2GMRFzhgEbr6+wSixPOZJMcC/tPZdt2cCl+HLtmSZed5TdnzGcodT7Em3EY8kNYaPFfIoOHi6e8w663A1TQ9uI6Zm5NDSt3lbJXD8A2XasZRirJ6/sZR+Rzeqx0bVqoDGXc2VHKxcr/Z2QP6+ZtAveLZj/0KXAH12/YihCPdzvt/PCVfUZXMXLOXDz+/0ve3yri1UYnwI44IfK4jpUiYkR3tfTg/4cRsfTrRfSN/hA/DyeNdEaw0550c4Ag5G6yXRbLMlcvCA071ZAiyz6Ld75Goa2nWauoXLKWEpdDq8qHV6mvOz6uPyqFgLwRIwv5ee9bLlsr5FrAiI76dKgP5xdNd/hWRO2yZJw==
  template:
    metadata:
      name: rabbitmq-secret
      namespace: default
    type: Opaque
