---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAB8z4ytRgRXaBTFKPn7pgM5+czD7J6Rn6/7o8DMTiJhRIz7RS9tWa/ucxqMe3whFzTkYTwvaep3Y4mJmst/c4s3PNSeEBdU1hu1UKKFa5A7nRLVL7Ey4ot4p+wz2NMTtZIybI/bK7IrJeqPKjXVUc5yslKMpugGOlR3JQFi6M55sOoKbBVAOw/0LmswF6OT+NEIczJE9x7hexLy9qGj4KOeWWnYS2PjfX74qt8nMcGYZFObV1B2eFl7rRVxzqUdcMRK//mcugXsVkyC2qHEtsL/KYFzqjRLkn7hxqWSnHw3QKj4MBLbg4T2g/4Cyb1THTAy0Ik5SzeSklPkqlgku9xZW0bn27LvZHGsZIGv/FDhVkTyWN2QbdYwIZjH4q/WW+BVm4LThiY2mgYFglJCuP7iXrux4VWU/5C5JQHuiypL1Ugj6eoQ/8/L+R2ccsLJDYkecHvsxJtT067bqeFZOLVm8fpzlgVzKt2VHCHLEsi4iD0d3Lz/lhBwqNDm1nVt7N+hlETW5nL3Tq0RFz9b7kUk8hrNrPiKSA85FxJHLOpBVeUXd/mvfDLPJgqmBxu8FVrH33zRgzHU8HIOs2BoQEfU/1bLQ2qjKVLhA16565kvZYI2IFX4ya6SnTpoYNM3WAuqA0taC1iAzIiSWVeq6oomIGswEuAub+qvDAU+lIsuk6CZEWHoTILF1q3jV+Zn5723jYJHNkpSo6LAKBd/b4cvkqwgdx/BjAtQamh7K+KBO6IZHQ=
    RABBITMQ_DEFAULT_USER: AgARVO7N4CofrICGHgRCDs4+zU5N1V0jVRUAP2B+cvB5uK1cWrP/MAWEtQHFQdt5Sv4jkO63yzPlA+BR6W7M9a0iMEifZgPICQL6SxgjlwseqRkR9A7mRd3e4VRNDcKGP9K7JACnN9AUnxzj1uExZH32BO0uZkpCHC0SPgnx+uUKwClJ04grYbqrj3lmYfdQUm4czP5FcDIB1qH3YXAuRVpohPq7JRebKE42dJgcf3zlCDVB2nL9feUvbBjmZZaA5T/n8cLzIpBBz+twDp0QoHgy3ZSTZIoiQtkVU+z31tIEUS/GM7VIk2MHIB7DstXfaHTri89sebf+YmWFh1JWq6TpcH7MMWWCmICjucRZwP/f43bv/DhQNpVEpTUxdW99Rn3W8OeNY3oeoyUstkzUAbkIrq1l64HUdOVl6Myn+ph6XLzpaGphcVyhYzGNd0eBjhzJbBwfFoG7TGcu1DVav8GiqJQRHAKnWjZ7vldbEx99fhaJ0+nl2CqjSxOMlFWjnBhN8lxohRXO+6hIQec2A/eCYZ7/3w/02IVnxkSutNQl6gHl4F5eSTnAV5fne6FvDRtViBPN0AouvqSVWYKn15zV5w7a1rYqUrWKa/gsRMlEI6ZHSA5inB6VTH3XgbISeo/ALstecXBmgrN90QKeib8SIAKAFKH15XWmq7bSZtt3u4ZNYEtP/Dk+zDOlsBEKU5cXpP/gmwj0f111ZD7lkvjL
  template:
    metadata:
      name: rabbitmq-secret
      namespace: default
    type: Opaque
