---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAgIZaaCq4isUS+QsvaR9OhCzM8m0myD+wLNSIvXI9MPQjYUOVvwWFpOHlNf8JSlMch1RG7vgLbP2bOCmDmEVPaIaIXDs7MYOUeNJLYPAD9smgzYMFJ7YH92Dx9JrmEbY9y6aBJfiM3ziCo1OY9t9fGWM2iboZhosIBtlrsF2yo/p24mTfeXbHW1UiCtpSdkuMyFH9jf191KGjjrThoii+BRR4Ii0OWLtGVka2rxBumibz2plyV0gja26a6fuE4j8g9vGZFZdRC2Q45gxxcs+1BqkjPzGZxCkxA07NXRyGx8bgvcaBsgSez5Xq78Oh/1Px6xnGa69Uk03kxen/8liTE7zecZu8ltbJG7KxhDZUn2ZikX+3jE4xURVjrCikHGFjOZsV3IV3vGYaqMZe08hT/9frTvyrk+tRjtZDJhhoYcFFmrA4CioycbRb7HqiNYvRPGXq1MRcfpC/UJhbMAyAzuIlasq8AH8dxyPohySlXoHub+h/TpcXipe+l12psZF1giMje/YLX2jdpv2JmzhaF0ogKKdAa/QYg5KVagJRzOhxZQhCNsStJAOcSfAFAS0nJ1DGj1qUddxQ4IOSrMZDUXD+1rSfvhBmu0IMcIyyleMoTi3btXt5O9Lbp8e/2b3yiIIXeGi35VLtGz6+QXORvZR015widHe5RUGH0qJmVR5CXrMMsELRlrqB4q3wuUnMezptaA//agtiyV5Krqx6y4s64/d/6MbfdLYW8A9jKS8FyiHQ=
    RABBITMQ_DEFAULT_USER: AgA414XHopZcyCTmjhmWWFwt4StvEs1Z9Mk6TqqTNEKfpYXBC5tSr6cbrQvq/vNTINgP4zAD2FTyAQRdvuVhrKXL/5JYsElkhGEOMT1+BpSNvrKJ27ZNR+Sp/44u0M8C7AFPGqMWTu/SXGNV1TFPdegQ18kBgvnc8/8NgGDTqVxiR/gRCDxTiZOz5RLHSWf0uFOnq48nVM8o5CQlb0gaZ7DwFhu/muHiCmFOijLGRy6GZEKfoweoBSjpNV5KfGEQrXRSBSq0tfXCJcMcDHyh6mP/llaKpE1MoucI4sHfxQW8VOALffO9QCnBwPgqXkj7d0y2DMKDPo0zzNPr3kxvKVJyVNICXV/G6aSU0dM6w0vaOLBB1akLmlUzG9Ekz3IT+cmC7el0bV/2m+Qdo/SnZHQcgruVSuneQ+t1yUVWeXl14pghK4eCzXHOVJT8lAscEmcscJyASd+1ugIMe42XzEzQU+j59KDUbKVvFkw0hufiTV3vyQPo9aIAFbGfEXXBW/sJe92sxcApet8OKKWy8ANDUVPinw0a5jusjZsgrPcfYzbMYeo47lNpUs5lKpmSE9Bv/xHPkMOh/aHmzzaQlC8b4MmTxQfFnHi8RcQzEtMEW5wItTv4VMUqam0+iUM23XbEPvjIzhNG7oI3He+oslZ1o7MAK+uUpnC7cWVhju6fK/n0rREXBxWuWI3d+jT6KzPu0VLLJh5QblmIX5px4/f/
  template:
    metadata:
      name: rabbitmq-secret
      namespace: default
    type: Opaque
