---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgDd1b4tkR2zoBu2r6yD35VY1189v8AwpHLTnnwh0wS3/WkkdCAlm/o8/WvinMBxCKucnkjr2Q/2Tho7gre9QeeNEBRFd7fOt9TaqiSPHXhiEa/zLHAU20lAaaBxXYg76eBAA2BF3Hl0AElNYPoJr9O+HtsKljukHozqr5jEGqOzH5iP6mlHTPKuFbPXENBXieBanPICf0sd9qey/jwOpasnwxDNCsXDwpKA608DLUjQR1VYT+Au9evfAYEvDrOxljymqr2HSifD/uerA7kSbROIW+dSvD2z4hIdlYegx/ABlSy+a3iM2wUAOUyb645Xjsb0Lfh50DY952DbTzsDus73oPFvhxkCzaQvejlEBaAnVnZpNzKz18oIP3PtvUQpeZy18/g8y71xJiwjwBBKl5XnJkvQqZSd+BK1HB8awrPXdhpJ4K8S1+IW5x0Tgoh+grnSU/tdThG1RigRlLmVvxSqZsuMRHSqIFyPWzOdpgH9KZL7FHdof5tcezE5hpMn7Ca2QxNEaVeyxliRo2c0URshhKtHU4M6F+lXcY5mAABL3U/DlD9pKwGD8mYm45jyPP7JsPgqG3xUFjbLPO3uuGjx7n7Q22pYFuqC5ZQ6Upa9BlRENiGhykQRry2sxKptGKTmdgb12OUB6B7mlALnDjn4rQbob3bIyaY/AJQJUYhtKHVlx5KYcWLStUNxMq3a+l3/8OfiwdfuNEYsnSx4g6pDPI53gv6SGMwyPMt1TfU=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
