---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgCnIIeVatv5T/QKAo46wVH6E9Nn7MLM6fxxgsVnAKHCKxOtkQ1vdutSLVyUtyIO75bi8/GDQ3WqJkbxk+BbbRD/zdbZZbB0mO4vSliMpXJ3GOh9llVkW1LLCfAsHn/CDIKRdVP2aOnWxUUvoOiY/BK0xbLXCvI7KgP/HdwaWUv1M+9vwcndvofbSQQoN0pcl7ODrSk/VbCe52CaIrpGUa+1NN1I6JgOaVELVf7lwWlWnlPnT2mz2AgLY+XgQ4FBiDDwc2hWwAKjeOcE/xbm5+teosGrxd5tIlpY2vTZX8Ouxk/9WA0/aBlBHnKGOamOOB+83l9P265hr07baYM8KMviEgtHVjkaS8wn00o298+O5VkdheXz39QYHm/U//qHH4YDXElHbdxO7lyvWnvgu2AOnrLbueUMjeO+WOfChRtr8a7+MjHDONiuibsyslYS72c+IOiGWPb6M6zrglqpxqk/BEPv4NsGdI6tCj0RRzL2L2mx/AEccypbaOOxV8ofHXDxZKDX1F+auZzhY0PnszLEBTtLxh/E0R1MgnmhaO+DtEmfagJhW7JzSok1e4oOuzlqx6+83rxnNKKllOuoZs1/I7FOjeGV8HUi4ti1OzA0aAtFHMCR3LIr9vufGi1ktHHlP8bzh8BU+PjAVQonBofhjkiWyBIycETLKqMs+07ZyRIicdeox7tIEOD0R6IzaMHxL7WWcU7fjdhFQroRHWZ6CdYXa9YMeb49o3N4hw0=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
