---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgCNDvHC5gRGajzeA1zfOlRVKLwt8n8i2yll55oGixrQJZ0GNGpynAf0LV09k/ZmfpXuFS6Orz7lKZvWaxGyV/vorKUPj1pE4c0QnekKgLWIThWS8jChtU4wpAqMJrciLLMQKUnYSPHfNj600WeifIXMDZpRz5vYyZ7QeOfZTnpanmv7YICt4+EaLRlssp5U0iWZKdt9H7g8E3vNYLUiwd7NfXI18MbdMw33A8c9mDmSPq1PEN8YfjIerG7ljOKlg5qyzqQtqhGA6l8Mlpj6Msg59Xhzjp/sRvg4O8CgNo/WUHyiG6dlI2sQ693lsV4jUkjiVb1HJ+Qm24oyOXHpB/YNfv3MhezEDg2AuYgMX99gpGimtp0CjSbRkVrJ3LscyhlWscZ+b2owJ6K4aijAyIdy5Wiobabjg0INX0NHtTAUimGIODJEEzKON83hjWZdXnkud66LupVRMAD7pfJiyed/HUE0++88b9jFi5CS6eVzanlWKk/65P5sz6xQ9/mbe1rMKt4vJwfWmXxd3H/x5ocVwJAPPKEFO4MNQ+5HoF8xeCteLoTyY5Kr7wKIvxtujs6vu1MPejXaNw5hyIFe3svomdZHzxsS+M/TLJDxxDmA+3675KspSyVV87UWBDKfP7PndPsGyqyW5MyiAtqh76KLq+QMB3D/8zBqQoBmj9O6TmQZs10Iw5ITHZFrMj2Z3OxDJv3I6CEqI8gQ+t5X7ZNSWIyWj4W3P6NUe3HXN1Y=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
