---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgCYwYa40PemAMW7UUglcLCD4m/lqrRmtTB/y0dlxQi2EleT/B/2GAaArpDuWw7giRv6Hy/WqNsoB/YvuKktcL5wKvRaZQ8XOK39CkMps91rkQk4+2A6zPlt8Y59Y4QAI8ZLLqaAyCG6UJoPBm/VAEd3mChwmN8K0UauBSOrRIWXtZFdMZwq0ppd5fb88yG6PDTHdnk7R7EoTan/XmLmAGmOct93813dLzsJnfNcwzOveuIyTYiDsUemQA1Fo/ml2mjyZs5MuL6kBEHKwGtVMNv2LrZtzsVx/tF9RLHIV1Ey+mP2MO2evmTb6TdvQf4oxtbcGnFXnZ0Sjh3VYMFc/+ZheuhmcCK8EPXpPP2tZluN8++tlnN1bL2KbbVXKGilOsDs8522fANrtNepzZHIFdWHc7z6PzEemiubAORlnB1Xw0CILCoSNaRUgg1UXlhGAqKs1utMrUcBfvCBG6NJgpQMW53MbTBc6VUlobStNopAx5P7Ggg5j1uVh48t1pMf8k6NYp4onkUR/PwhOTqkJodNu4SUDq8rBq1p27gpv0t3Qu3Sq8fPpGnXZod5XxIMOHIvM7onAFV6IZaBhmubatC2tFqfT3tME246yKQNLd1hocvy596S3//4/Uq3vlynlV3UFxdXc3BluLSD9p/40HEmmo3bcFJWGsurYg9ZI5l1/WPXzxcOdVxOu9af4H5KV0TgO9sphJAdjbXfDv02IA12K3llqJWiyTxYjaZ4S1g=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
