---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgAy4jQRdHo5TXP+vDkhPP5zcK6yWg6kt34xOzRWiqLM6dvHzmtJdGbaGd+hTkm7d1/tieizglaTXNwt2Uxvf84E7jZLVSJe1N84QC+h7yHEAqiDTrf+aGlxBr08UE2irOxjUu+bNLJNBuoe/pPwuY4OKUDur2bg12M1BtwbOhpxKydnsN1Wkz53IL0TYCOCXQDZotWpQ61WWwagc6PqqlkANd20K7gIQSvNzVmgQHKpJ6rXDuAzkjD3oea17Xy0BksTkBSx4aPcZt7Vge5rDUaNQwVmOjmpOqQH2CAQ4kSWgNQacfVIvrKRxTNEx3a9O4idW0cMg7qrTRqgkllL91hyQ/4BwUL7nEIrUmBmfse0dSdMk8uD2ZYdwVcDUZVA/DCz/9CWU3EGkd5RHNNO5MqVeAiFe92CONkBkwNlnLTNXv4Xjb1PHmy1EJGUDr3aj346ZazAS3DmUyuiJ/mE0weXh7EdvrkaXv4RQsl1idETx9bITkCArJ7RGAG6y68Yf0OPFPpFA3LW/5hhDKTjcX6AmVUqNwWycbLvAfc7os4S/cX5sjzfe0N3MDJ8zjWG0nXcJv5tSjg7pmaF11jQ6Cf+MP3ntwI+rYuP3EWw1odClASCLxognnd8uEiLgfQ61X4Tlzgni0sPBOIo7irNtbb/+ELutgeTRfbUfGyjHIOagHESpYlt8ZEoLvn6Qv7Hsr9tK06+NpkYc/SMXbE2XH8VZ6B/QKxXxUBUUU8RBi8=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
