---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgDdFYY2sstCaLgkm58rLYOad9Wkn9zQbzzQk+v6T6pL5ZSYpRFIwxmSpxpTpg4R6ohyxwr7nt0h8Btr2lLaTluydA4Mq0+zgEe7SvSOgh0GjimW1nRwZhLl1W6c/K053eYYmhwVYRLbxZ6LZ4tpfWIcVN6Z5aavHGlCseZoULt4YYNpEmT2yXeLDCYO67E0NWB2dFb047ih7bOtv8thi9mO3Hn/j+x1Sg5rz/HI8w7YKwXFziY6toRCxABTfdM1iAkXzWuCbF3xLw5Ql7w0m6ExPUxbARw0BNYvIVXX4AME45ACgEcoDukfRQEKfxi3flxzT53Rl9DJdrQ20AQxtVAsr7NFg0+rHFsadVB8kbMDQiezOPuF3rVG+61QODpFKTrn0JdWZbDPxCQUBcmkODPNcyRsG8SLGjGTi9ldWuKyux37wjW6BNwh8Qr4q9QpsYt1HIYbXFKYbNzNxfalMjKmod4X3O/wSar8Yhp3XF0QeBZEmRZF3/ia0a35Y8hprflzL1stKiHvHPR87bYTxwl+rdRBksrReIOWfJOWg6jwj+SwISuOXPK/SOcOQb1Eng2Eu91W6D1wheWrY8VTGUh36YL499vS/LIKXq0mmecqKp5bNX8l3X/3vlLxivCqCEtlHFVawIjHrP7iVYrIwsIUh8fv0n9OYvgtheKJroeFchJSRfyqHi4Mr2SUOiCTbEsI6LNdwTw6iBgiSLR3qotjnJmj5VOPsY5vhGmWRBM=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
