---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgCiMVCqhtbKkWMRawGCU3aqF3uWX1AD8pJJLrSfQKKxPzeEIOjKNySGo49r5ziJfIqylMUUefddAz4pHblwQTUlKih/PSZ2RayL6FIJ4CnJJHp8/8gyHP0GbD39POYbMH0fEL+sRYpdZcDo5twHtme/CgTvgcbGfpqYPoi0ILHn4c8rzfF9h7VRewz7Bee2XUv0d31YtpmGcM3LyuLG738gh81y2StT/6zCQJWijihsXZxzYHL0UMU4VkSuY8vQJs2MYvyrErFHxYtdez3dPhSWDQ0fZQJGczjntJBsptwU6ylDgg19+GNoK3z5Wm9pzSnOqTYgvLNzNl7XcRMF00h+OHQAEY5SdhCTl5ml54tWKvVfpPd9kPPh6IO5hp8VbxDFOE7zYZOAiUXDaYCv5/ksfd+YP6KeprarRQ1SrtL1Qv76aARO3W70pPjgA3kBzPlm6qyxeIs4gyoasHztpvEl7FWySCa2tPWqp8lkDMho4tPPqtUvtReVwFHokCV6/mVABff0+MHne2NkehPcWC6FTeQxjCFTD3y4mY59hRblEt2mgOosQXC6133j2zGJaFeDuIry38QXNZORZ665zdN8z+A7ohm13yC/6Wt/GuWMOXWrxMw/G6LjXUOf2j/X8ZMMaAazPh7Ye3k1oEFuNNsbWRo9wpoHFYTTg2g3LWxarlaDwfZdqmXU0oV1zzV8k1BMcizZDcR0dko+e2fRBWLndC63929W9j4Lobzs8sE=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
