---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgCAO7lB2x6sn/oPFyLrwMoyHughQPlmxQ611TAGJ+G5RiaQgf2ZFB7EshAjJgu+My0dl98aHGF0MF1pZcN+BcgdbBEh1M7KAir8KxvJYbu+TBokewIHPWVEbaXjwTg8s75OLcMWGP2K7RtTBNwOdpO9YJ6aY77DhdR4BEw4MeLmjVVCPqa4siku66H5hv+LYFBF4Yu5ePxeohq18nxP2jySd4pJN7BYXaGz4TsDLAJMCEtO82b9QFYM7UAhakDi2mczDowwV736Lf0uB38HGf8Oj/iDSDqkLSbBhf4bNIgB+KAx3fxtiWVFL3nJSd7BZxyA1cVusJdB90mKbM+uoClPtBxf8v0A9yrQbGWVf6LU1wNGGQw27PIYFuUvV57wAZKVs242KQ8IzO1zvpzAkOp2FKubGme0L8QhhAUgQGsgNZi6lubKN4J1MukLzJU4zAHwPcWJ4xk15PLd8tgU5I9bmqlv/omdjx+Bji86+nNiIS8MZwaDBAdS0T4W0Twyi3lCX8qr9DqwhtJg/oWyMTCsaXGW1BNSjN7fXetiK/aWvb9iufL1JHNv+5mNJMYGhMhMRE6A1mZiGff076hkOZIABmTM5JqmfB8mkata2jULazFdQuYx/nwzQxmVGHqeBc1fxMzSjnx0q4BOqZvwbVeDBW/TH4uERQ+cPA+nCTmiYcpC4jAlkvpN8ZN37TGQr+TzjfwDKQ4i1RhQ4jqVdvSgU5zgKsdnzkrxa0EvZBQ=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
