---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgCqHoXK3kfFzaVuBcXdS1KH+7SU85cFSHugov432yJY16/Unh8EMbPsvkEc91W8yq8NBAoZbvrqoeHZjU6guT26w5Yn5OXLkNKdRP3mUwP9HeHvVnU4RjDMYcoYo1kkOS2ZLJvGBYbKyS0EOdR/bTDylcQAeI9RUK2ui/J7f1O6KtCjgv10gjfXsZJ+dWZh6AhEf2czm/cct/RYfVezP1GTRBh56xZS0RPObD1U7wBUWg7ElqOp7ScHnnGvzi28ptE03MakfPT5OyLrL198OjdwemcStajoXWV4pfDF/+iALdZl3QdUpXvryScJ2YZpiA7QRxEHDW6WR75nRd6acMjmwwIINrNnF3dhcx/YORl6DM9dRebUVcL9/sUqBhStS+k3P5jJIUxU7G7edtW20d+8oo0nWYHcgdL5wkpGn5Bn5ejjHl9RIul9LTOa7okg5tYtJiLnLnZDtc9N7l/TPg483LpjSX9CYYjAaEeay80QZG9KFJGESe8sFHwpQzKbJDxMNKKfOxRnSScR6L/ea3FCRaUEcRGolUtYZgiIpGcgOTdi1H8UXlivsU2bUnaQQhQ+iGMkJocD9gcCa6+WjVd6/FksRXjT4mUYVv2sRfzZwNZYaYZaXYf/BsJwW6jV/vobZjnq/sWLDv9RPgJqqi95J8LpR99Z7UE8s1umr0Y4z+FQWEEPGCDWT0H6p+fodFYmQSJz0wECduvY41JAQwkvACY03iSFmZ6t60clKZE=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
