---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgBM4g9EbJDn1krjM/utsWp7If2sWkDEgxg885im6LvYrvk8ZE773+8J8QYlS4WHr3E6RvNrPThq83K/fHFzV+tDA0toobq8gBxjorfTYAqyUXvnrHlpFCZyx4Lo4EGh5L+XOD8RtymaU1r+ZVb3MIJycO4ufoBaRhstpVEESygMzecKuwmr2ui5xx7dxYmGhFtT+n3U+DUFxSB5Momq1UW/BI4fUW49f+5LwUAnI22IMZsGTKfXyBXZFgWeZ7TQhx3QbW6PKgFM9RP3DzbPiNionHGFSlEc2xjuORqS7V64DaXZ53F1al3YY/+FjrO7ws6eioBgcr1oxm66xpaV/HyPigWKi/c/6HwhlmLQ/PKSaLD97820BDz5mToYqww0huPsTr3yXWHZcFq5tlGbpk4UdhPdOsBxERbLNTnf3DT0ZRQhhSKIm3/r2tYN6gnYRiJIp+oTffuZXPUqn0DAyoM7mQ5a9hB/xo0OcXgWFR/BTHLYvDAIkH7AiZoiwOse+mmGLelfChwsSzXqpNbn+L0hO4xY3lDCbNsMkLvW6tksahoySsQvJ99/g0/VLy/aYIYLj4Dg9z4h+Yx2LrT9kizMvRr7tTFVZ8rtNIlrskyAXZt7OoLjtTpVgz/It/0+DGoozt+WDo3VXIEWN4XTZsDm9MBma5HxmFE0fp1plguB46ZXHxl+okQEAZGjmp/nhIfxHE7KI3/DuRX18P2pvTnhNkmH+XG5C//hejFNpH4=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
