---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgAO2dheSzDgamONTd85UY/uXnme0rwhXYssRmCh+TFVZy1rvRmkxzwOsWVd6OqoAG7EvUpv50tcgSvP5NM5Tw3cE8dLwoKSpNFy3hXCWg2+RW1/x5hK6D7Z0OUre+h8Jxe87vbde4hro3CUlCWUOOMkptLUJu4g88wYe0kEkV0eNJMBCz60+Zscp6jp8vYe9GeU7KxPMEcPkVW8nBv1CtdVSBCrEz1htR7HMYGeD9oCrqD0uKkerOGpWZo9Sx+LoUGh/Yl8didccZ3jbyXLrEQt1Da9P1fKRDiQvH7F//lA89lz9DsjcmbKWtNlD/NbNK8lbaytI0yoKhksfdePy8vCaWE/fzWjNTJbDEQz8702HVUf4a0BoS1fgVbNwJejgtF7le/NDFC5n82sBsvsNBNAivkg0bjyjioAw6e6Z2UBtiLKOX2Xn3QUT4gGPn/G8LGlEeMJ34Ks7CQouyjYbO3IZAs2XF2l5kz7t76gVsX4kBFwtXlWE+tp5u+wVA0cfZ+mAwxc2sHv9wJE6RYGm6qpjY2tihgsjAr99O4x/9VFEJm/SLOTaJy9zqGhggameRb2VjFeAZXo3rYAaxWpEsEJOe9IX4k1lmqOSOSjq8qw6dzIuUSTqVjfkKdKixi9G0YoCCITNBtrcE1XVz2ofbCeplSvJ4I0aFFXTr5K5kU9KKabg6BXhtNsLKH+xIB1mTo2zjqBjxpD3LINkBfz62xdYjZNfXIt5sQrbUnc24E=
  template:
    metadata:
      name: postgresql-secret
      namespace: database
    type: Opaque
