---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jpstudy-app-secret
  namespace: default
spec:
  encryptedData:
    password: AgBij7xWSkyddVWDRVX9GlNQOHv+zmnsXznjYUzvsqRIlxFX3Z+1Ou033FC2dA4GYJenNRHbVhBNaRuJHvTYEo1dDzlpVKUjzpvkbFOIpPdDVEKRVMkLyWW+ASOQ5PcXyPuGm9vtdJ9gAQ1phNZD81irJYkMgnXVNa6J7kg3HVnqnzAfS9hZHzo+xLcN+wr4jwqy4Xh4nWWfAvltNHaOj11AGRGYPzJnR+NvPTk0OlPW69B4FBLUHapNhx5syZ7ctGUD10iRgkjm9FFmTxdd/PKSDkQAKVLKyflKoZcnfdWL5GeVy9tS3MTjYrtbh5J44L5JSg0GdLkzjL1X4p6hlrZn/WS8n8I9KzYggF44mEtRUc3IidjJcmmky+0ihY9lVVkHBZX52MGqB2Ub2GW/e+e1iDDIvbIg2jzmAfX61saj37KZ2KRrkZUEbfOBAJdLWAqioOFchK/CjbmfRIwcLmm/WeyDk/27Xy7KsX/8VF8Z7ywGi1FI/ZnygIjXkgiWloxkRITbLR+lrFXlPjEYfuV8Kl3L2OynlvaFzFbS1r7KO3eo01hLA59quqJwScyg/QBdiETz3f5reyF6Hn1KjObnS48YlxJqABrL+578K1tx0Cj+jGx0PaLDDWJIRmEY7lhG5YpRIihyo8t16y4xRwHv9ZsWhDbuIuFt7HZ3Ee9AsMXadjEPzIYbOc7U1d8IJbKaCLvA
  template:
    metadata:
      name: jpstudy-app-secret
      namespace: default
