apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 23.1.1
    chart: redis
    helm:
      values: |
        auth:
          existingSecret: "redis-secret"
          existingSecretPasswordKey: "redis-password"
        master:
          persistence:
            enabled: true
            size: 10Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true