---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgCOCBsXCmUiheiqql7jyrdgylJqIQUCBoj0qcfU8F1gLsvlDVrF7ATWiW3v7p1YWv4zj0fshGSppqXujdxVW/Ae43qrJSFw3CWH5BIfG21AFOfTGdO/WFnmvsNq9tXNyib/B2gv+nBINe/QCCX1yxZ3FgC0dCcO54Sug0JMcVL33myKYFNMFIpaW8Kxd/U4hNU9QlToeUHiN2ImjKEu0CTG8ExJ/a1WwHvZ4Q0gyUIW6bRI/IPXtDa1s/tfI9dd/Kh8dLo3Y0P/sgKyTG6Q60tKk3pW8Mjxwe45hWrc/00bs11t2RRTxH3SMi98pMWxL+IFKoys5w5RJzGyzuFGjhIKr5zNroihkepE7PbxZHyUZr8KgGXodR7PHVf1Iw/NBQPhpMOT32h6Efz6Rq1DtVkObUO2yghbiEf+r17ua7NkngW72zNoWXscnb63j1jGFV2prHIBQ0b1HnWRsliLdaG2DE8Z9o/mFDAV2//nPqlBCsE8GdFxHqGnsAOCgOvaWC9hRpvSZlVplJWYwyh8u1IQz2yWq1XIyHC0CFfsYGdJmpnsWi8L2xUgAh4Z29UhbqFAIFkvc9mOKsqwiuubBfaGAvssWNJTCIHL8eUzVGitOko5a+dhyT5YlUFwuZlkmYDIk6RWYl9SAUnH9Pdlpi8Jz5raLBKVqmejykrcT3E8ezoCa1pAyF+iHtBJlyCtQgEnsD7IklhTSKzk+e6ZFlM86nQRwDygiAhAhVX4F7E=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
