---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgBfuM9YXNnCzj82GPS0pJCXmZkqk9ouk/+vlVsw0b/nx9M3dImwStiN02hYKulUx5CY1dQtRTDovWyzLPa1aEyq7RCwA+xA89WO1v4xe5Cw6CjeKUd9sPIE7QJWMmSDf5ffy4k/1Gl2qiBmlY0cSsj0ssu4/SeycG5njXyPbp96zNfXVWALCEW2e20SUy0HaPhRCsxzyIwGHqJMPZsnEO/4nw4T+bwEIBY7bkDtIL5aOJ/clSEjjENExTqBGTfQVw8PYtpU8wMDrjzSZ/EHZ9cVBWYlpaMuNmObSLVuj0yOqeEDEkKQayEvzWKCZHUFG2x51dNhI8g1fxAmDutaBkA9wCD6lEnsefDPFMg9rJVbTtNrn8Z+DAF76kJ/so1VM2Z9wVfdwxAyjwAWM0ZGgD9NB/6Hkme5/Ryn+7hMdm0DHTCYFlSqpYgtTlZ1l4WfWBLzQ9+MJ5ZljaEujQBghxR8JXNy5s/5xxK1g3rEJPPIUjlnqbPEkdDMvBDiQxJtM/KkwUFMUifEH1p1CHPTmiC7ktlizY6pf4yvIyvXoilH8RzbbU4+jZgaJuN3K4EZB/6o/9I/fZGMuZK4ye8TwU+1eJ94TOMquGx9ipYdzeFmxf3WaRbF2CkUOfgbycM5lUUdaoeRMIx8eiQLeoBUPxdtdHcFzUGkxrb7uc82cNhtAu5Mvj/ZlUVWVCj0TmCXLYlB94gVxHiJlX6fvZ9TgD136DMw++gSYbn0yQs9Yhw=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
