---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgDSfUiWiposuQ9B/QPaQrRv3q5EjNUVB+D/r1bQuy/Q0pNHNsfkzHvb+lixqFBXh1zrsz9y3dfArKzA6Wr7E2QZWi21prhk+rQkSkTS7Wdk8Zne7flzQGFwEVZGW7yPtV8Hwo2Sg9UW5j6Ewgw3qqBSsJV+6f7qu1y/KOORKzH1FNlRQe5zn9W4O8ngyoW0pJnCtI5KmxkLCQFhj7zf/HHcDeekqy8By9s+WvxH6ByKlkaNYKcMTsF//15XfKxWRDky4VbT+pX0tPUbfk5ScqHRTOWJhjywQHzetY/G1RH+b+uZLFk7wGMPCts5lUZ5yHhTFwGsSiNcUCJ33PRLiwXkfY84uyV0IB2i7MhCBr/7JDw9kygQrpCHFTEe7O5r9E77cc6/yVXLkhHP/3nDts2L6IiNNodJ3Rb3yYrnO4iX1GSZfLzFwclVgo/dEoqtvSeqi6Z4LjUbqq5VUwPdvMrdlsA8bG2TVwCzFNHghtb292GP0ghsB2n39i8tdC/jlNEfXghkqW9Rc8IQGdBXUCM2dAp2WBnUHZElmnFxopIYf9iAik5rnMt3c1D1V7IVIpCsz88ab0YaZTKiekGBJ3jOcYYIs56nw0kVsV16psdfMu0OERb2HK+RmteTU6THvg0PDTNo8HNzAvaR/BbU5Tqzh4HN8FK+p1kuGH+SCRFaFgYHbfxKSs5FVFbR5Y7PSrztPe5V0RWdNrVrI0HOv9UVQv6a++KYWUkLsHE9pso=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
