---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgC0+OEJ9P17FiBJWAELPmwAG3E4xKU4DFyW2QNi3jISXraAepKDFNBiJDTVRsyseMiSxagxp1GyGCRycknxUGYrcbBRf3yFhDV3ws23zLAYT1tF+IQrLvREDrSdgtelV++5mx5tcqOPvIiGiwI9FuhnTwO5A4jURBdBg2AurAcONDV3W1mj0+I1+VUIrj4PvU2XMxCxtcbthSf4QAPdd+ZqrszRG/5nhIblUGq8LpqobyUXF7Ec31CepniR0Sihuk/ojnKR/a4GFSInhkNHRla5Nh60oZDI9uB+a8WnHOJPhCq3zqoYOrnbc7MLsqQTB5ljwf+6n/mqGSqbyK8h2XZqPYjmblR3DhL5T3QSIAztVBRP5Sfqpxigzps8D5M8vzvS5ewaiLDJy6uI/GEuot+81iGFJG/6u2TzoUG84FFbuapGyHHCp9YY4grVaDkJjXj9fGATTnPbQPBog9DwQtAcsCLMQxbjoqmGptRGmAQ0Tf4gkeRhoZehz/lAld8RBid3doIE0PoXedm8sJj14FeXNmRy08NDw28OHKbR8kdQ8ASMM8s9H9e3IV4W7PU27RyKm7dH6U+JqtRE7VUscGguk0NRIpabu16WRjzYM4is9wHeggtfh+p54Qrg2vDjk9nR6tyN7PTKbDW4RapDw8KkrsfQMYrfQaHWA+bq+D/cAFXNE82kI9A6w8UZeZolvDWc8TTS0MSo8/O7bYcesBWVStNzHKqjAQpjprcahSs=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
