---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgAZW8psPTOLrrZ7MgTSnDglyYlhXQoBt8VAc3VEWVhSBuHN3duB+6Q/sWO+PUVPwRD4utDKinobnndLmRcbRrHRLVb6YcfzVIR9WIFPp0lFcRt10B63j6HuDiSyQkd0u/0ADt1383fV5w+SbHHYxWMvdbnvVRtd1MIQiOb2gwsmUutCO70baZe4c8OzBYp3McuzUT75aLmM57J21cGpBj8pWXG40D71dU0fIYHT+UQvuqAtRZ9UHlQckE9xo1cRJG3GoFML1rOtHgEyND3VzlMXURXtrg3/MNYRo5/B0CuYzw8NC5gKmGJ5xJDPhNM3QM8dp/BETvf0XU4g5spJ7ySz/uM/7Ox0ZC5c5t5FCHkBG53oRorOxbJ4V84Nd8VGDz+lvwAwJZLIcGE/FpFJMuV9/pN2HK8nEXidDfRA2rbtR5U+FEGNWv3uOBAryTnag1Hfo2oVvFh7eIlnGc6+OlFFgOPeEGr7gx6byahO8tvNMQ1DnliAFBKk6CSRWuxXEs872M2iQGk53P6vbbwHsACl1Lj2h8x/nK4AlT8aHfrYitIdsWQIHI5a+Y97zUmn1wiBqGbN6iEFYkNEVJssYW7rXwxnjKwxil3y4SeKOjjXtRWNJYxemKnr+x9PjO5g7ZCjtu7t0q/wL3c4oOksk2CEuJigpNLKpMTxuX69G1dtdsXiQcOuTJnp9DmHOiGJwFxJZIoSvz1fryOwXLJ+EtBRvKvGcjfhVggDLTQp734=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
