---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgAqUU5h6zTHqqfnLjLVJHb/V1QktqhT/KbYxnn6OuhoSDxpxbo0S+i49HnYmFcBcgDpLCvn1fuu6iSdicuNSVLJhn+SsW2wd9ZLjyuYSw8mB/AuLkly+JWKK5arDx8s3zOhY+1AJ0Lzgjp4A313atsAfuHPCRW+kBFqCf4ijSKIbCXiYGl6odDqF0cEsRF0isYU+1Icicby2VzUZ9yPYZSHU2/qG04xNjlVjfX203I0n9TEd3KffuHJX9pDA7S1AERrdA7X2FMnG08v95fUq44LCWtv2HZ8V03NoZqN+jJpqcRW9MydmMzGDLxiy4Mn+2cEpHyAbF6KCRQ1JyAntWxFNU+SKDnESXz7aDMJVC5nzcELBUz1+GJmxXtItU9H+EIXwtaOWop/IHGLp0hTaXT/PGpMkIxIs+q3CCiO0kO1VX/JZeQZdJBQyL/8rKV6wALZWHAVXVsHhKV5Jx89+Kmr7seVgGucK3CfWwajzgdX1jyDa7bR5b2oB18ptOA80g6/YfgiZc5p8cNUdBYOV8XOinIKOOZnDc+Nn7XGuBhRA8AhQ+IKFFxdj/tokp0nLfKrkIwTFx8WWalggFYx4n3yHhHbHFUArKTyQ4/f12b0W/LlR3YnLrXoSCBEyay0DptkkrMa5C3hfsiFZyd941xmwEAx7fx2Q9qVnw+56WiEBOMHCUJ8V8EWoyCWFq+4nRAOV0QzSgMpOdE/nQ/9V8CfDCZAU6qiwuBck1sGH3I=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
