---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgBhRyDzGA31e+O4Jw2NIs0T6QErLXj4WK3G09SLVPOZ1RleDcCguUchDdGqeXcXjpRu8ZJ753PohW/GMpytNG2Grj3Oms7ux9hAig1GDMpDKdrGnTjkxGWREbQTdB3y8d821XOFOQNn72YnjpxO8CFmxgtIR/4rXbrTv6qYdEm9KSDHMDIEg6SYI8uiiU5UeEwvdNzPc1T3OH2NqpOo8XVGM69N5xTejMGXN+8SB2cedg8WQHCR/nMQt1ThZPZyNiNvVaWY2H6sMyvohrb0ryJ9PtdzSe5CHI0kT88RYpcYlgkVyOTllbmVYDXf519FqaGW2v/A73Mvy7WDXHUqkq35mL+D87USE+Mxh7nLAkq5UTYB5rUFWMg1H2mMPbXfH3Nyu+ZVA/JB0GnIb8k2/9l3YxK/m17LisSasxgH+a5h6RcQjT/ihsubDbY9s6jOLKpFgk9QqQ07cjXtHEfbLMFbclC0KG1757rxMNpX3aAdfxkfIPyez86A8ubr2uDKlxlFfcx6G2xvN5AVVIY3tmFOkJlk0tDHoJLExnx9R0koTZXU+l9TxMWVgbg6DoEo6lIFJUgJ5jp5TRwHDDlFc/NLp6S1oj3ORrvf84EYpHu64kzv3sWmwBRQDQNX7NKSIf/4kDq/57/YLnzzpPMCCWnP5IcFNHJ6VpfKlyXMsOEzcl4aK4EuUtn+dlh1a3fG6docD0au55hgMSYRKggcoFJ0E95SGyOeFmCvpPFt9/0=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
