---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgBnIGl3woZ58Rid3ztvpRGMRiCf2s4PWpfwtd/VobPMPwM9QlclVDaaDcv5ZD+/TKjAiLUgWIFlg/9m2IYnEaG9eK2WKTPc4JLSd2x3GyjNYUlEl4A8Iz6tT/6VOEL7iVXJv9EG/pAIdl3T4tQYd625YUSMBk6sAIJaLw0EdaKZKg6KxVu2bVqwxL6tV4lBAZ99kAUJNNfRRoV5b6p1QXTAfJZk6Vk3MeIaDA+FoKo1+y7Q2JM6uCRgclHzmXmJ7ihGCgkgQkem1b7Hwb6zbuKyVulNhsIZVfe6V6fm9SGXpHrYw3mWRvBSd4ls5PLvz82IiPGFudaUmG/pez34AtGgtO3edEwnjVQ3xqJxg+FOjeLHTlhRmmgIa3EUHTQREN2zefe3PIrUPKxzbxFnVS/gl0/3Gqhl1gH6RUkEiI4p5qjfi21MH8KT+h71dpC2q0ZX6l1QtdcXkJEPs3vZyWb4OZaBPuzcFLVFqqdOo/JAL3rKm5tIFhqKMBM2A7zvFBy2+VgNTDRBQaVFLUzSpZKCGVoOVUiXcNjveZnVVYLljKJ0msBNP6R9Os22Sxv6hx3qnvp4/G1xw0P2MruW1HW7yBVihFeCOeuc47MDug2Rg6zBCv6WhydlI+PiIYH5XvdRI7c/7ES/Pz4wTJswhSfGDXfCUBjbaC9Jv7AP8aUkKmgXsw6saV0mI6Ha9mvDD1nzaix7GarJzd0S8Eaw45sIJLlm/GCkJSrYm+Y0JA4=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
